# Generated by Django 6.0.8 on 2026-08-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products',
                to='products.brand',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(
                blank=True,
                help_text='Technical specifications (e.g., RAM, Processor, Display, Battery)',
            ),
        ),
    ]
